# Generated by Django 5.0.4 on 2024-05-23 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactmodel_id'),
        ('employee_page', '0002_employeecontactanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecontactanswer',
            name='employee',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='contact_employee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeecontactanswer',
            name='employee_response',
            field=models.CharField(default='test', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeecontactanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contact.contactmodel'),
            preserve_default=False,
        ),
    ]
