# Generated by Django 5.0.4 on 2024-05-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='test',
            field=models.CharField(default='n'),
        ),
    ]
