# Generated by Django 5.0.4 on 2024-05-12 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_form',
            new_name='ContactForm',
        ),
    ]
