# Generated by Django 5.0.4 on 2024-05-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmodel_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='test',
        ),
    ]
