# Generated by Django 5.0.4 on 2024-05-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contactmodel_test'),
    ]

    operations = [

    ]
