# Generated by Django 5.0.4 on 2024-05-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
