# Generated by Django 5.0.4 on 2024-05-24 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contactmodel_answered_contactmodel_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='employee_response',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
