# Generated by Django 5.0.4 on 2024-05-09 01:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_home_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
