# Generated by Django 5.0.4 on 2024-04-21 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Review',
        ),
    ]
