# Generated by Django 5.0.4 on 2024-05-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_review_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='url',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
