# Generated by Django 5.0.4 on 2024-05-07 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_review_author_review_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='url',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
