# Generated by Django 5.0.4 on 2024-05-09 01:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_alter_review_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='url',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
