# Generated by Django 5.0.4 on 2024-04-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Meal', 'MEAL'), ('Drink', 'DRINK'), ('Dessert', 'DESSERT')], default=0),
        ),
    ]
