# Generated by Django 5.0.4 on 2024-04-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='ingridients',
            field=models.TextField(blank=True),
        ),
    ]
