# Generated by Django 5.0.4 on 2024-05-25 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_method', models.CharField(choices=[('COUNTER', 'Eat-in: Pick up at counter'), ('TABLE', 'Eat-in: Table delivery'), ('TAKE-OUT', 'Take-Out')], default=0)),
                ('table_number', models.IntegerField(blank=True, null=True)),
                ('order', models.TextField()),
                ('state', models.CharField(choices=[('NOT-STARTED', 'Not Started'), ('IN-PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cancel_reason', models.TextField(blank=True, max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
