# Generated by Django 5.0.4 on 2024-04-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('Eat-in: Counter', 'EAT-IN-COUNTER'), ('Eat-in: Table', 'EAT-IN-TABLE'), ('Take-Out', 'TAKE-OUT')], default=0),
        ),
    ]
