# Generated by Django 5.0.4 on 2024-05-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_cost_alter_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost',
        ),
    ]
