# Generated by Django 5.0.4 on 2024-05-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('Eat-in: Counter', 'EAT-IN-COUNTER'), ('Eat-in: Table delivery', 'EAT-IN-TABLE'), ('Take-Out', 'TAKE-OUT'), ('cancelled', 'CANCELLED')], default=0),
        ),
    ]
