# Generated by Django 5.0.4 on 2024-05-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_cancel_reason_alter_order_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('Eat-in: Counter', 'EAT-IN-COUNTER'), ('Eat-in: Table delivery', 'EAT-IN-TABLE'), ('Take-Out', 'TAKE-OUT')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('Not Started', 'NOT-STARTED'), ('In progress', 'IN-PROGRESS'), ('Finished', 'FINISHED'), ('cancelled', 'CANCELLED')], default=0),
        ),
    ]
