# Generated by Django 5.0.4 on 2024-05-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
