# Generated by Django 5.0.4 on 2024-05-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('COUNTER', 'Eat-in: Pick up at counter'), ('TABLE', 'Eat-in: Table delivery'), ('TAKE-OUT', 'Take-Out')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('NOT-STARTED', 'Not Started'), ('IN-PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default=0),
        ),
    ]
